### ISSUE TITLE
Template not working in OSX (Monterey)

### ISSUE THREAD

**Issue by jrosengarden** [libopencm3/libopencm3-template#12]
Hi.  If somebody could help/provide some guidance on this issue it would be greatly appreciated.

I've been trying to deploy/use this template in a Mac environment and it doesn't work due to problems with the makefile.

When executing the 1st command (from the README.md file):                  make -C libopencm3
it errors out with:                                                                                              GENHDR  include/libopencm3/stm32/f0/irq.json
                                                                                                                           env: python: No such file or directory

and the file actually does exist at ~/myproject/libopencm3/include/libopencm3/stm32/f0

I followed the README.md instructions and entered this command in my home (~) directory:
git clone --recurse-submodules https://github.com/libopencm3/libopencm3-template.git myproject

I could really use some help here.

Thanks!

**Comment by karlp** [comment]
try editing https://github.com/libopencm3/libopencm3/blob/cb0661f81de5b1cae52ca99c7b5985b678176db7/scripts/irq2nvic_h#L1 to say "python3" instead of "python"

The form we used was the python recommended approach when python2 and python3 were still in widespread use, and the script runs with either, but if your system doesn't _have_ "python" it doesn't work.  We may wish to revisit this in the near future if "python" is less available than it used to be, but that's an issue for the main library repo.  Feel free to re-open this if that doesn't help.

**Comment by jrosengarden** [comment]
KARLP:

Thanks much.  That helped get me past the 1st step (make -C libopencm3)
Now, however, it's failing on the 2nd step (make -C my-project)

Here are the error messages (and I think it's still a python vs python3 issue);

JR-iMac5K :: ~/myproject ‹master*› » make -C my-project
env: python: No such file or directory
env: python: No such file or directory
env: python: No such file or directory
env: python: No such file or directory
env: python: No such file or directory
../libopencm3/mk/genlink-config.mk:47: No match for the FPU flags
../libopencm3/mk/genlink-config.mk:52: stm32f407vgt6 not found in ../libopencm3/ld/devices.data
../libopencm3/mk/genlink-config.mk:63: ../libopencm3/lib/libopencm3_.a library variant for the selected device does not exist.
  CC	my-project.c
arm-none-eabi-gcc: error: missing argument to '-mcpu='
make: *** [bin/my-project.o] Error 1


Again - any help would be greatly appreciated!

**Comment by karlp** [comment]
so it's complaining about missing python again.....  the genlink-config.mk is trying to run another portable python script: https://github.com/libopencm3/libopencm3/blob/master/mk/genlink-config.mk#L27-L31  you probably have to change that one too.
