### ISSUE TITLE
Additional Problem with Template

### ISSUE THREAD

**Issue by jrosengarden** [libopencm3/libopencm3-template#13]
KARLP:  (I added this to the closed issue....but added it here also since I wasn't sure if a closed issue would be 'seeable' by you and others).

Thanks much. That helped get me past the 1st step (make -C libopencm3)
Now, however, it's failing on the 2nd step (make -C my-project)

Here are the error messages (and I think it's still a python vs python3 issue);

JR-iMac5K :: ~/myproject ‹master*› » make -C my-project
env: python: No such file or directory
env: python: No such file or directory
env: python: No such file or directory
env: python: No such file or directory
env: python: No such file or directory
../libopencm3/mk/genlink-config.mk:47: No match for the FPU flags
../libopencm3/mk/genlink-config.mk:52: stm32f407vgt6 not found in ../libopencm3/ld/devices.data
../libopencm3/mk/genlink-config.mk:63: ../libopencm3/lib/libopencm3_.a library variant for the selected device does not exist.
CC my-project.c
arm-none-eabi-gcc: error: missing argument to '-mcpu='
make: *** [bin/my-project.o] Error 1

Again - any help would be greatly appreciated!

**Comment by karlp** [comment]
(already replied on #12 )

**Comment by jrosengarden** [comment]
Karl:

You keep closing these issues too fast…before I have a chance to test/insure I’m ‘out of the woods’.

It turned out there were even MORE scripts that were failing so I decided to just create a “python” executable with a unix hard-link to the “python3” executable.  This way the scripts that were calling for the “python” executable now work fine.  

NOW I’m out of the woods and having a working libopencm3 Template system in place.

Thanks for the help.  Much appreciated!!!  

P.S. - The reason for needing the template is that I want to ‘get out’ of using the STM32CubeIDE and work at the command line and the libopencm3-Template is the perfect solution (solving all the INCLUDE’s and LIB’s  along with the various constants and declarations needed for the various boards).  So now I’m TRULY out of the woods AND out of the IDE!)

Thanks again!


Sent from my Rosengarden email Account



          
Powered by Mailbutler <https://www.mailbutler.io/?utm_source=watermark&utm_medium=email&utm_campaign=watermark-variant-primary>, the email extension that does it all
