### ISSUE TITLE
How to enable printf with float argument?

### ISSUE THREAD

**Issue by profOnno** [libopencm3/libopencm3-template#4]
In the [libopencm3-examples](https://github.com/libopencm3/libopencm3-examples/blob/master/examples/stm32/f1/stm32-h103/usart_printf/usart_printf.c) repository there is a usart_printf example. When compiling the examples this `printf("float: %f", 3.21f);` works as expected.

Using this repository (libopencm3-template), the `printf("float: %f", 3.21f);`  doesn't do anything (skips the line). Some searching did reveal you should add `LDFLAGS += -u _printf_float` to the make file. This didn't 
work for me. Any pointers on how to make this work? 

update: 
Got it working, added `LDFLAGS += -u _printf_float` to the `Makefile`. Not sure what went wrong the first time.

**Comment by karlp** [comment]
Doesn't appear to be anything else needed here :)
