### ISSUE TITLE
clone and go fails at step 5

### ISSUE THREAD

**Issue by MpeStuntPilot** [libopencm3/libopencm3-template#5]
The clone and go instruction work fine for steps 1 - 4.
On step 5 I get the following :

mpe@ubuntu:~/mpe$ make -C my-project
make: Entering directory '/home/mpe/mpe/my-project'
  CC	my-project.c
my-project.c:2:10: fatal error: api-asm.h: No such file or directory
 #include "api-asm.h"
          ^~~~~~~~~~~
compilation terminated.
../rules.mk:126: recipe for target 'bin/my-project.o' failed
make: *** [bin/my-project.o] Error 1
make: Leaving directory '/home/mpe/mpe/my-project'

The OS is Ubuntu 16.04.2
The ARM tools are installed, and libopencm3 build without any problems.
From just looking at the directories, everything looks to be right.  
The directories specified in the Makefile look correct too.

**Comment by karlp** [comment]
my bad, forgot to add the files.  should be fixed now, sorry.
